name: Accuracy Report

on:
  workflow_dispatch:
    inputs: 
      lingua:
        type: boolean
        default: true
        description: "Generate accuracy report for Lingua library?"
      language_detection:
        type: boolean
        default: true
        description: "Generate accuracy report for LanguageDetection library?"  

jobs:
  report:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Accuracy Report
        run: ./build.sh report ${{ inputs.lingua && '--implementation Lingua' || '' }} ${{ inputs.language_detection && '--implementation LanguageDetection' || '' }}
      - name: Write Summary
        run: |
          cat accuracy-reports/report.md >> $GITHUB_STEP_SUMMARY
          