name: Accuracy Report

on:
  workflow_dispatch:
    inputs: 
      lingua:
        type: boolean
        default: true
        description: "include Lingua library?"
      language_detection:
        type: boolean
        default: true
        description: "include LanguageDetection library?"
      ntextcat:
        type: boolean
        default: true
        description: "include NTextCat library?"
      compare:
        type: boolean
        default: false
        description: "Allow fair comparison across detectors by using same subset of supported languages?"   

jobs:
  report:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Accuracy Report
        run: ./build.sh report ${{ inputs.lingua && '--implementation Lingua' || '' }} ${{ inputs.language_detection && '--implementation LanguageDetection' || '' }} ${{ inputs.ntextcat && '--implementation NTextCat' || '' }} ${{ inputs.compare && '--compare' || '' }}
      - name: Write Summary
        run: |
          cat accuracy-reports/report.md >> $GITHUB_STEP_SUMMARY
          