name: Accuracy Report

on:
  workflow_dispatch:

jobs:
  report:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Accuracy Report
        run: ./build.sh report
      - name: Write Summary
        run: |
          cat accuracy-reports/report.md >> $GITHUB_STEP_SUMMARY
          